apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mypapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mypapp 
  name: mypapp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mypapp
    weight: 100 
