apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mypapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mypapp 
  name: mypapp
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mypapp 
